apiVersion: v1
kind: Namespace
metadata:
  name: prefect
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prefect-worker
  namespace: prefect
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prefect-flow-run
  namespace: prefect
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prefect-worker-job-manager
  namespace: prefect
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete", "patch"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prefect-worker-job-manager
  namespace: prefect
subjects:
  - kind: ServiceAccount
    name: prefect-worker
    namespace: prefect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prefect-worker-job-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prefect-flow-run-reader
  namespace: prefect
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prefect-flow-run-reader
  namespace: prefect
subjects:
  - kind: ServiceAccount
    name: prefect-flow-run
    namespace: prefect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prefect-flow-run-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prefect-flow-run-sparkapplication-manager
  namespace: spark-jobs
rules:
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications", "sparkapplications/status"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log", "events", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prefect-flow-run-sparkapplication-manager
  namespace: spark-jobs
subjects:
  - kind: ServiceAccount
    name: prefect-flow-run
    namespace: prefect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prefect-flow-run-sparkapplication-manager
