defaults:
  namespace: spark-jobs
  driver:
    cores: 1
    coreLimit: 1200m
    memory: 1g
    serviceAccount: spark-driver-sa
  executor:
    instances: 2
    cores: 1
    memory: 1g

jobs:
  - name: etl_job_1
    application_name_prefix: etl-job-1
    main_application_file: spark/jobs/etl_job_1.py
    arguments:
      - --source-input-path
      - s3a://prefect-demo-data/raw/listings/
      - --target_data_base
      - processed
      - --target_table
      - listings
    driver:
      cores: 1
      coreLimit: 1200m
      memory: 1g
      serviceAccount: spark-driver-sa
    executor:
      instances: 2
      cores: 1
      memory: 1536m

  - name: etl_job_1_dq
    application_name_prefix: etl-job-1-dq
    main_application_file: spark/jobs/etl_job_1_dq.py
    arguments:
      - --source-data-base
      - processed
      - --source-table
      - listings
      - --dq-checks-rules
      - s3a://prefect-demo-scripts/spark/configs/checks.yaml
    driver:
      cores: 1
      coreLimit: 1200m
      memory: 1g
      serviceAccount: spark-driver-sa
    executor:
      instances: 2
      cores: 1
      memory: 1536m

  - name: etl_job_2
    application_name_prefix: etl-job-2
    main_application_file: spark/jobs/etl_job_2.py
    arguments:
      - --input
      - s3a://prefect-demo-data/raw/news/
      - --output
      - s3a://prefect-demo-data/processed/etl_job_2/

  - name: etl_job_3
    application_name_prefix: etl-job-3
    main_application_file: spark/jobs/etl_job_3.py
    arguments:
      - --input
      - s3a://prefect-demo-data/processed/
      - --output
      - s3a://prefect-demo-data/processed/etl_job_3/

